plugins {
    id 'java-library'
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    api 'com.github.StarDevelopmentLLC:StarLib:0.1.3'
    api project(':api')
    api 'com.github.StarDevelopmentLLC:StarSQL:0.1.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}